stages:
  - build

.curl-tpl: &curl-tpl
  variables:
    GIT_STRATEGY: none
  tags:
    - curl

check_author:
  image: docker-registry.linagora.com:5000/lgs-releases/gitlab-integrity-checks:latest
  stage: build
  variables:
    GIT_DEPTH: "1"
  tags:
    - ultralight
  script:
    - check_author.py check "$GITLAB_USER_EMAIL" "$GITLAB_USER_NAME" --no-accents
  except:
    refs:
      - master@linagora/lgs/linshare/products/linshare-ui-admin
      - tags@linagora/lgs/linshare/products/linshare-ui-admin
      - /^release-.*/@linagora/lgs/linshare/products/linshare-ui-admin
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

build:
  <<: *curl-tpl
  stage: build
  script:
    - echo skip
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
